-- TABELAS (sem constraints nomeadas dentro das declarações)

CREATE TABLE usuarios (
    id_usuario SERIAL,
    nome_completo VARCHAR(150) NOT NULL,
    login VARCHAR(50) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    data_nascimento DATE NOT NULL,
    cpf CHAR(11) NOT NULL,
    tipo_acesso VARCHAR(20) NOT NULL DEFAULT 'CLIENTE'
);

CREATE TABLE enderecos (
    id_endereco SERIAL,
    rua VARCHAR(150) NOT NULL,
    bairro VARCHAR(100) NOT NULL,
    estado CHAR(2) NOT NULL,
    numero VARCHAR(20) NOT NULL,
    complemento VARCHAR(100),
    cep CHAR(8) NOT NULL,
    id_usuario INT NOT NULL
);

CREATE TABLE telefones (
    id_telefone SERIAL,
    ddd CHAR(2) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    id_usuario INT NOT NULL
);

CREATE TABLE competencias (
    id_competencia SERIAL,
    nome_competencia VARCHAR(100) NOT NULL,
    data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE usuarios_competencias (
    id_usuario INT NOT NULL,
    id_competencia INT NOT NULL
);

CREATE TABLE produtos (
    id_produto SERIAL,
    nome VARCHAR(150) NOT NULL,
    tipo_arte VARCHAR(100) NOT NULL,
    preco DECIMAL(10, 2) NOT NULL,
    id_usuario INT NOT NULL
);

CREATE TABLE pedidos (
    id_pedido SERIAL,
    valor_total DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    data_pedido TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDENTE',
    tipo_pagamento VARCHAR(30),
    numero_parcela INTEGER DEFAULT 1,
    id_usuario INT NOT NULL,
    id_endereco INT NOT NULL
);

CREATE TABLE pedidos_produtos (
    id_produto INT NOT NULL,
    id_pedido INT NOT NULL
);

CREATE TABLE cartoes (
    id_cartao INTEGER GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_usuario INTEGER NOT NULL,
    numero_cartao VARCHAR(16) NOT NULL,
    nome_titular VARCHAR(100) NOT NULL,
    validade VARCHAR(5) NOT NULL,
    codigo_seguranca VARCHAR(3) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL
);

CREATE TABLE imagens_quadros (
    id_imagem_quadro serial4 NOT NULL,
    imagem TEXT NOT NULL,
    imagem_public_id VARCHAR(100) NOT NULL,
    descricao_foto TEXT NOT NULL,
    dimensoes VARCHAR(100) NOT NULL,
    id_produto INTEGER NOT NULL
);

CREATE TABLE pagamentos (
    id_pagamento INTEGER GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_pedido INTEGER NOT NULL,
    id_cartao INTEGER NULL,
    chave_pix VARCHAR(36) NULL,
    valor NUMERIC(10, 2) NOT NULL,
    numero_parcela INTEGER NOT NULL,
    data_pagamento TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL
);

CREATE TABLE recuperacoes_senhas (
    id_recuperacao_senha serial4 NOT NULL,
    login VARCHAR(150) NULL,
    codigo VARCHAR(250) NULL,
    tempo_expiracao TIMESTAMP NULL,
    usado BOOL NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NULL
);

-- INDEXES (mantidos)
CREATE INDEX idx_enderecos_usuario ON enderecos(id_usuario);
CREATE INDEX idx_telefones_usuario ON telefones(id_usuario);
CREATE INDEX idx_produtos_usuario ON produtos(id_usuario);
CREATE INDEX idx_pedidos_usuario ON pedidos(id_usuario);
CREATE INDEX idx_pedidos_endereco ON pedidos(id_endereco);

CREATE INDEX idx_usuarios_comp_competencia ON usuarios_competencias(id_competencia);
CREATE INDEX idx_pedidos_prod_pedido ON pedidos_produtos(id_pedido);

CREATE INDEX idx_pedidos_status ON pedidos(status);
CREATE INDEX idx_pedidos_data ON pedidos(data_pedido);
CREATE INDEX idx_produtos_nome ON produtos(nome);

-- Agora as constraints (criação centralizada)
-- Usuários
ALTER TABLE usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario),
    ADD CONSTRAINT usuarios_login_key UNIQUE (login),
    ADD CONSTRAINT usuarios_cpf_key UNIQUE (cpf),
    ADD CONSTRAINT chk_cpf_length CHECK (LENGTH(cpf) = 11),
    ADD CONSTRAINT chk_tipo_acesso_opt CHECK (tipo_acesso IN ('CLIENTE', 'ARTISTA','ADMINISTRADOR'));

-- Endereços
ALTER TABLE enderecos
    ADD CONSTRAINT enderecos_pkey PRIMARY KEY (id_endereco),
    ADD CONSTRAINT fk_enderecos_usuarios FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    ADD CONSTRAINT chk_cep_length CHECK (LENGTH(cep) = 8);

-- Telefones
ALTER TABLE telefones
    ADD CONSTRAINT telefones_pkey PRIMARY KEY (id_telefone),
    ADD CONSTRAINT fk_telefones_usuarios FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    ADD CONSTRAINT chk_ddd_length CHECK (LENGTH(ddd) = 2);

-- Competências
ALTER TABLE competencias
    ADD CONSTRAINT competencias_pkey PRIMARY KEY (id_competencia),
    ADD CONSTRAINT competencias_nome_unq UNIQUE (nome_competencia);

-- Usuários_Competências (tabela associativa)
ALTER TABLE usuarios_competencias
    ADD CONSTRAINT usuarios_competencias_pkey PRIMARY KEY (id_usuario, id_competencia),
    ADD CONSTRAINT fk_usuarios_comp_usuarios FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    ADD CONSTRAINT fk_usuarios_comp_competencia FOREIGN KEY (id_competencia) REFERENCES competencias(id_competencia) ON DELETE CASCADE;

-- Produtos
ALTER TABLE produtos
    ADD CONSTRAINT produtos_pkey PRIMARY KEY (id_produto),
    ADD CONSTRAINT fk_produtos_usuarios FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE RESTRICT,
    ADD CONSTRAINT chk_preco_positivo CHECK (preco >= 0);

-- Pedidos
ALTER TABLE pedidos
    ADD CONSTRAINT pedidos_pkey PRIMARY KEY (id_pedido),
    ADD CONSTRAINT fk_pedidos_usuarios FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_pedidos_enderecos FOREIGN KEY (id_endereco) REFERENCES enderecos(id_endereco) ON DELETE RESTRICT,
    ADD CONSTRAINT chk_valor_total_positivo CHECK (valor_total >= 0),
    ADD CONSTRAINT chk_status_opt CHECK (status IN ('PENDENTE', 'EM ANDAMENTO', 'ENTREGUE', 'CANCELADO'));

-- Pedidos_Produtos (associativa)
ALTER TABLE pedidos_produtos
    ADD CONSTRAINT pedidos_produtos_pkey PRIMARY KEY (id_produto, id_pedido),
    ADD CONSTRAINT fk_pedidos_prod_produto FOREIGN KEY (id_produto) REFERENCES produtos(id_produto) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_pedidos_prod_pedido FOREIGN KEY (id_pedido) REFERENCES pedidos(id_pedido) ON DELETE CASCADE;

-- Cartões
ALTER TABLE cartoes
    ADD CONSTRAINT cartoes_pkey PRIMARY KEY (id_cartao),
    ADD CONSTRAINT cartoes_numero_cartao_key UNIQUE (numero_cartao),
    ADD CONSTRAINT chk_cvv_length CHECK ((length((codigo_seguranca)::TEXT) = 3)),
    ADD CONSTRAINT chk_numero_cartao_length CHECK ((length((numero_cartao)::TEXT) = 16)),
    ADD CONSTRAINT chk_tipo_cartao_opt CHECK (((tipo)::TEXT = ANY ((ARRAY['CREDITO'::character varying, 'DEBITO'::character varying])::TEXT[]))),
    ADD CONSTRAINT chk_validade_length CHECK ((length((validade)::TEXT) = 5)),
    ADD CONSTRAINT fk_cartoes_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE;

-- Imagens Quadros
ALTER TABLE imagens_quadros
    ADD CONSTRAINT imagens_quadros_pkey PRIMARY KEY (id_imagem_quadro),
    ADD CONSTRAINT fk_imagens_quadros_produtos FOREIGN KEY (id_produto) REFERENCES produtos(id_produto) ON DELETE CASCADE;

-- Pagamentos
ALTER TABLE pagamentos
    ADD CONSTRAINT pagamentos_pkey PRIMARY KEY (id_pagamento),
    ADD CONSTRAINT fk_pagamentos_cartao FOREIGN KEY (id_cartao) REFERENCES cartoes(id_cartao) ON DELETE CASCADE,
    ADD CONSTRAINT fk_pagamentos_pedido FOREIGN KEY (id_pedido) REFERENCES pedidos(id_pedido) ON DELETE CASCADE,
    ADD CONSTRAINT chk_numero_parcela_positivo CHECK ((numero_parcela > 0)),
    ADD CONSTRAINT chk_pagamento_um_metodo CHECK ((((id_cartao IS NOT NULL) AND (chave_pix IS NULL)) OR ((id_cartao IS NULL) AND (chave_pix IS NOT NULL)))),
    ADD CONSTRAINT chk_valor_positivo CHECK ((valor >= (0)::NUMERIC));

-- Recuperações de senha
ALTER TABLE recuperacoes_senhas
    ADD CONSTRAINT recuperacoes_senhas_pkey PRIMARY KEY (id_recuperacao_senha);